### PR TITLE
Resolve #25: Automate deployment

### LINKED ISSUE #25: Automate the deployment of healthchecks-front

### PR DESCRIPTION
**Pull request by jimmyygit**
On push to main, deploy to dedicated branch https://github.com/WATonomous/status/tree/gh-pages

### CODE REVIEW

**Review by smilesthesad — APPROVED** [review]

**Comment by ben-z** [comment]
Lgtm! In a followup commit, let’s delete all of the static assets already committed to this repo?

**Comment by jimmyygit** [comment]
I agree. This should be completed by https://github.com/WATonomous/status/issues/7. We can probably move everything in `healthchecks-front/` one level up to the root after that

**Review by ben-z — APPROVED** [review]

**Comment by ben-z** [comment]
Oh wait a second I need the all.html copied over as well

**Comment by ben-z** [comment]
That one is useful for the infra team to debug issues

**Comment by ben-z** [comment]
Also @smilesthesad did you use a personal access token for this? I think we want to avoid personal tokens as much as possible. Otherwise handoff is going to be a mess

**Comment by ben-z** [comment]
0E021648-550C-495D-BFC2-18400DB8AE29

**Pull request merged**
